### ISSUE TITLE
button layout aesthetics

### ISSUE THREAD

**Issue by SEOJIAF** [Juriij/Quadratic-Generator#5]
### **consider tweaking the button layout. It’s not a big issue, but it could improve the overall aesthetic.**
---
### New button layout
![{6B10DA12-CE39-4757-A77F-B99A1E7C94DB}](https://github.com/user-attachments/assets/efdb8921-a371-4f19-97a1-2f665e2731ce)

---

### Proposed css code:
```CSS
body {
    font-family: Kanit;
    margin: 0;
    padding: 0;
    background-color: rgb(211, 211, 211);
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.container {
    height: 90vh;
    display: flex;
    flex-direction: row;
    background-color: white; 
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); 
    overflow: hidden;
    border-radius: 30px;
}

.right-side {
    width: 80vh;
    background-color: black;
    position: relative;
    background-image: url("Img/math.jpg");
    background-size: cover;
    background-position: center;
}

.right-side::after {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: linear-gradient(to top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 1));
}

.logo img {
    display: flex;
    width: 8%;
}

.left-side {
    display: flex;
    width: 80vh;
    padding: 40px;
    justify-content: center;
    flex-direction: column; 
    background-color: rgb(248,252,255,255);
}

.text {
    font-size: large;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
}

.header {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: row;
    position: relative;
    z-index: 1;
}

.About-us, .Guide {
    display: inline-block;
    text-decoration: none;
    background-color: rgba(248,252,255,255);
    color: rgba(2,19,98,255);
    padding: 10px;
    border-radius: 20px;
    margin: 10px;
    cursor: pointer;
    transition: background-color 0.3s, color 0.3s;
}

.About-us:hover, .Guide:hover {
    background-color: rgba(2,19,98,255); 
    color: rgba(248,252,255,255); 
}

.download {
    display: flex;
    margin-top: 20px;
}

.download a:hover {
    background-color: rgba(248,252,255,255); 
    color: rgba(2,19,98,255); 
    cursor: pointer;
}

#but {
    display: flex;
    justify-content: space-evenly; /* Spaces buttons evenly */
    gap: 20px; /* Adds consistent spacing between buttons */
    margin-top: 20px; /* Optional: adds spacing above the buttons */
}

.button-container a {
    text-decoration: none; /* Removes underline from links */
}

button {
    font-family: Kanit;
    font-size: 20px;
    text-decoration: none;
    background-color: rgba(2,19,98,255);
    color: #f4f4f4;
    padding: 10px; 
    border-radius: 20px;
    border: 2px solid rgba(2,19,98,255);
    transition: background-color 0.3s, color 0.3s;
}

button:hover {
    background-color: rgba(248,252,255,255); 
    color: rgba(2,19,98,255); 
    cursor: pointer;
}

@media (max-width: 600px) {
    body {
        font-size: small;
    }
      
    .container {
        width: 90%;
        flex-direction: column-reverse;
    }

    .right-side {
        height: 50vh;
    } 

    .left-side {
        width: 100%;
        padding: 15px;
    }

    h1 {
        margin-right: 30%;
    }
}
```
---
### Proposed HTML code
```HTML
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quadratic Generator</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <div class="container">
        <div class="left-side">
            <div class="logo">
                <img src="Img/logox2.png" alt="">
            </div>
            <div class="bottom-left">
                <div class="text">
                    <h1>Quadratic Generator</h1>
                    <p>Software tool that was created to help high school students practise quadratic
                        equations/inequalities. Math teachers can use this app to automatically generate and print
                        expressions to create a small math exam. It may also serve well to substitute teachers who do
                        not specialize in mathmatics, but were asked to do revision during the lesson.</p>
                </div>
                <div id="but" class="button-container">
                    <a href="Quadratic-Generator-EN.zip" target="_blank">
                        <button>Dowland english version</button>
                    </a>
                    <a href="Quadratic-Generator-EN.zip" target="_blank">
                        <button>Dowland slovak version</button>
                    </a>
                </div>
                <div class="license">
                    <p><a href="license.html"><b>Read License</b></a></p>
                </div>
            </div>
        </div>
        <div class="right-side">
            <div class="header">
                <p><a href="guide.html" class="Guide"><b>Guide</b></a></p>
                <p><a href="about_us.html" class="About-us"><b>About us</b></a></p>
            </div>
            <img class="background" src="Img/math.jpg" alt="">
        </div>
    </div>
</body>

</html>
```

### Thanks for hearing me out!
